export const BRAND = {
  name: "Vibe Music",
  shortName: "VibeMusic",
  tagline: "Your Sound, Delivered",
  description:
    "Vibe Music is India's trusted destination for musical instruments, pro audio, accessories, and expert gear advice.",
  supportRole: "Gear Advisor",
  phone: "+91-9876543210",
  phoneDisplay: "+91-9876543210",
  phoneTel: "+919876543210",
  email: "support@vibemusic.in",
  siteUrl: process.env.NEXT_PUBLIC_SITE_URL ?? "https://vibemusic.in",
  domain: "vibemusic.in",
  address: "Mumbai, Maharashtra, India",
  logoPath: "/brand/vibemusic-logo.svg",
  headerLogoPath: "/images/FINAL LOGO VIBE MUSIC GUITAR 2.png",
  iconPath: "/brand/vibemusic-icon.svg",
  cardName: "Vibe Music Card",
  financingName: "Vibe Music Financing",
  gearExchangeName: "Vibe Music Gear Exchange",
  studiosName: "Vibe Music Studios",
} as const;
