# Generated by Django 6.0.4 on 2026-04-15 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='instrument_condition',
            field=models.CharField(blank=True, default='New', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='instrument_material',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='skill_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
