# Generated by Django 5.2.13 on 2026-04-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productmodel_instrument_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
